  version: '3.8'

  services:
    db:
      image: postgres:16
      environment:
        POSTGRES_DB: bankdb
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: password
      ports:
        - "5433:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data

    app:
      build: .
      ports:
        - "8080:8080"
      depends_on:
        - db
      environment:
        SPRING_PROFILES_ACTIVE: docker
      volumes:
        - ./src/main/resources/application-docker.yml:/app/config/application-docker.yml:ro

  volumes:
    postgres_data: