spring:
  application:
    name: Bank
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/Bank
    username: postgres
    password: admin
  liquibase:
    change-log: classpath:db/migration/db.changelog-master.yaml
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: none
jwt:
  secret: 7jk534l5k7n7b5j4kl3lfjk8v95n487g8df93n58v
  lifetime: 30m



#Что нужно сделать:
#  - Указать настройки подключения к базе данных.
#  - Указать порт приложения.
#  - Настроить параметры безопасности и JWT.
#  - Включить Swagger UI.
